export const FETCH_PLACES = 'FETCH_PLACES'
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS'
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE'

export const FETCH_GEO = 'FETCH_GEO'
export const FETCH_GEO_SUCCESS = 'FETCH_GEO_SUCCESS'
export const FETCH_GEO_FAILURE = 'FETCH_GEO_FAILURE'